export const Mentor =[
    {
        id:'1',
        img:'https://www.it-time-academy.uz/assets/RUSTAMBEK-MAMADALIYEV-D7sNZ0ID.jpg',
        name:"Rustambek Mamadaliyev",
        techer:"Senior Frontend o'qituvchisi",
        about:"O'n yildan ortiq dasturlash tajribasi va besh yillik o'qitish faoliyatim davomida 500 dan ortiq o'quvchilarni professional dasturchilar qilib yetishtirdim. Zamonaviy frontend texnologiyalari va dasturlash metodologiyalari bo'yicha chuqur bilim va amaliy tajribaga egaman.",
        telegram:"",
        linkedIn:'',
        github:"",
        techno:{
            react:"ReactJS",
            vue:"Vue.js",
            angular:"Angular",
            type:"TypeScript",
            node:"Node.js",
            aws:"AWS",
            ci:"CI/CD"
        },
    },
    {
        id:'2',
        img:"https://www.it-time-academy.uz/assets/G'OFUROVA-GULBAHOR-Coefen8F.jpg",
        name:"G'ofurova Gulbahor",
        techer:"Grafik dizayn o'qituvchisi",
        about:"Grafik dizayn sohasida boy tajribaga ega o'qituvchi sifatida, o'quvchilarga zamonaviy dizayn dasturlari va texnologiyalarini o'rgatish bo'yicha katta ishtiyoq bilan yondashaman.",
        telegram:"",
        linkedIn:'',
        github:"",
        techno:{
            adobe :"Adobe Photoshop",
            illus:"Illustrator",
            figme:"Figma",
            ui:"UI/UX",
            after:"After Effects",
            pro:"Premiere Pro",
            corl:"CorelDraw"       
        },
    },
    {
        id:'3',
        img:"https://www.it-time-academy.uz/assets/ISLOMBEK-RAHIMJONOV-BAT4FK3F.png",
        name:"Islombek Rahimjonov",
        techer:"Frontend o'qituvchisi",
        about:"Frontend dasturlash sohasida boy tajribaga ega o'qituvchi sifatida, o'quvchilarga zamonaviy veb-texnologiyalarni o'rgatish bo'yicha katta ishtiyoq bilan yondashaman.",
        telegram:"",
        linkedIn:'',
        github:"",
        techno:{
            react:"ReactJS",
            js:"JavaScript",
            redux:"Redux",
            materal:"Material UI",
            bootstrap:"Bootstrap",
            git:"Git",
            webpacs:"Webpack"       
        },
    },
    {
        id:'4',
        img:"https://www.it-time-academy.uz/assets/BEHRUZBEK-NAZAROV-CMQdpnpN.jpg",
        name:"Behruzbek Nazarov",
        techer:"Frontend o'qituvchisi",
        about:"Frontend dasturlash bo'yicha tajribali o'qituvchi sifatida, o'quvchilarga zamonaviy veb-texnologiyalarni o'rgatish bo'yicha katta tajribaga egaman.",
        telegram:"",
        linkedIn:'',
        github:"",
        techno:{
            a:"ReactJS",
            b:"TypeScript",
            c:"Next.js",
            d:"Redux",
            e:"Tailwind CSS",
            f:"Git",
        },
    },
    {
        id:'5',
        img:"https://www.it-time-academy.uz/assets/XOLMATOV-DILSHOD-HMNqAXeu.jpg",
        name:"Xolmatov Dilshod",
        techer:"Python o'qituvchisi",
        about:"Python dasturlash tili va backend texnologiyalari bo'yicha tajribali o'qituvchi sifatida, o'quvchilarga zamonaviy dasturlash asoslarini o'rgatish bo'yicha katta tajribaga egaman.",
        telegram:"",
        linkedIn:'',
        github:"",

        techno:{
            a:"Python",
            b:"Django",
            c:"FastAPI",
            d:"PostgreSQL",
            e:"Docker",
            f:"Git",
            linux:"Linux"
        },
    },
]